# Generated by Django 3.2 on 2022-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('num', models.AutoField(db_column='NUM', primary_key=True, serialize=False)),
                ('workplace', models.CharField(db_column='WORKPLACE', max_length=100)),
                ('floor', models.CharField(db_column='FLOOR', max_length=100)),
                ('team', models.CharField(db_column='TEAM', max_length=100)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('type', models.CharField(db_column='TYPE', max_length=100)),
                ('perpose', models.CharField(db_column='PERPOSE', max_length=100)),
                ('office', models.CharField(blank=True, db_column='OFFICE', max_length=100, null=True)),
                ('os', models.CharField(db_column='OS', max_length=100)),
                ('genuine', models.IntegerField(db_column='GENUINE')),
            ],
            options={
                'db_table': 'asset_status',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='mysite',
        ),
    ]
